allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  a2b4f040-f7b6-4cfd-a73f-626b686d1144:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-13T21:35:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0e8f02c9-10ab-4442-9b54-151202cde741
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb554041-611b-44bb-9643-c75629f2c8fd
        userCondition: null
    thumbFieldKey: null
handle: article
hasTitleField: true
icon: null
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
