allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  46c2c21c-2084-4830-8ede-1d3ea1dffe26:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 46e0adbb-5c7a-4b0c-876f-d1f5bfdca53c # Featured Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e50ca61c-ee22-4601-81ff-33fadf9c5ac9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1f1e0b5a-e874-40b9-9a54-cf6acef1dd94 # Body
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dac4068-664c-4f9d-b5a2-4b06bfe1e981
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 19b82513-b9da-4646-a2fd-d68c021bc39f # Full Name
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0820510d-8887-45da-a8f4-e7370fa3eb41
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ea2701b7-c19a-42f4-bfa6-673e90079acf # Birth Date
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 053b1721-4b33-4e91-93b0-d37c5599801a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e34dff31-185d-469b-9dc0-528a82120aac # Birthplace
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b920237-8d81-4826-86f3-cb5980424ca8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 345bc614-72e5-4974-baed-bef72b54a866 # Death Date
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80fae374-63fa-4b17-83ea-d019359076ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9d1def6-30f2-4133-8bb0-2b222faad34e # Burial Place
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd47ad04-6682-4804-bbb9-ecef80bae340
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 73a69018-cf55-4606-bb7b-d8a9e8b1a2d0 # Occupation
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6407fc89-f6f1-42fc-bd4f-a1642c78b72d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 68e6a476-a21e-4f5e-bd09-3668de8c50ce # Author Bio
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 665f5408-c22b-4594-8b4b-00bedfe24c61
            userCondition: null
            warning: null
            width: 100
        name: Identity
        uid: 87408374-03db-4515-bd4a-8ee312ccd9ff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fdb7f91f-2ca8-4df3-b40b-ed08f4227c9f # Spouse Of
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14f9688a-4f4f-4947-b560-6375b5157f1a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 80f1e2a4-562c-496b-a74e-5b9715a20d8d # Parent Of
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a26ebc3c-95d2-4e8a-9477-f28d91ea7229
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0043c112-7178-4dd3-a3ee-602d9127ed84 # Child Of
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da5ecd6b-0fe1-4006-8f2c-a11bd37dcc12
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 19daf868-e058-424b-ad9f-d24eba29d9b7 # Sibling Of
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13b9f062-37a9-45d8-a6fd-5102c89cdfd2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dae6ce48-c5e5-4e45-bad8-4d5dc73348b1 # Related Persons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dbf7641-6820-4e4f-852a-dff349c8e31f
            userCondition: null
            warning: null
            width: 100
        name: Family
        uid: e2677b6a-3f24-4f0c-a8da-70f1bf608c16
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 23d034f3-39ef-4b79-abc8-90d90848af4c # Person Organizations
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec8cf1df-98c2-433e-b0a0-aba4fb31ec82
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5ac21908-ed47-472d-ad63-d351ab78ec3e # Person Groups
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eabe455c-d460-4835-b29b-9e365c435198
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6cea5dc5-06a2-4154-94c8-463dfeec41d6 # Person Events
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 427531ca-aa44-4fc4-83e8-83d8d0bbf141
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 506d9eee-d8b7-4646-a6ee-df8151946554 # Articles About
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9b396bb-71c4-43de-9c75-5952d29e156c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1b1e1845-f71f-49d3-9032-e609d3014117 # Person Obituaries
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 726ffa30-dc74-42cc-90de-41f6ab201fbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 564391aa-8033-46f2-bbbf-6d65ac723b28 # Related Military
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 466ee752-7185-4a93-b3b2-e40f4a1ce21a
            userCondition: null
            warning: null
            width: 100
        name: Connections
        uid: 3fa71560-d613-4ed8-853f-82d2a24d7531
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 14e21ca9-0e1e-4188-b24a-a00381ce2367 # Person Wikipedia URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e84b82b-ec85-43d0-9395-a611697634b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7f2b776b-bbf7-4fd8-8f9f-4f9e5b3ef56b # Person Find A Grave URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67322910-9a46-4817-bc91-f25fd90694c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 869c1a3c-de72-4539-9c4f-c2a66302a5ad # Person Legacy URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f8b3976-230a-4a3f-ba67-e8fc1573a763
            userCondition: null
            warning: null
            width: 100
        name: External
        uid: 7e8620fb-62b5-44b4-9338-da006ac9a5f7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 554b9680-0f62-4708-b169-40c1d6a371cb # Person Webmaster Note Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9aff74d7-f90b-41dd-bd26-f93a0c0f5239
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5f666556-bbe0-4999-b3db-cf58e10d2fb8 # Person Webmaster Note Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f9df22-8371-4022-890c-58fbb8a02a57
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 600ba13a-cb0b-455e-b5a3-ce47481e5ee5 # Person Fine Print
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4bd47e2-f45b-4d88-93e0-7ee2e229b756
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:27:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f0a5c7de-ccc3-4005-84ee-53feaafc26e9 # Cultural Sensitivity Note
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07f3e514-092f-43b1-bf5d-e8de91e7114b
            userCondition: null
            warning: null
            width: 100
        name: Notes
        uid: 5fd0e679-d19b-4d62-9da6-98f509329aa7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9a795a95-5db5-4474-951f-38f5f2fdd6d6 # Historical Era
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71ebc414-58ee-4043-a607-bd24103e0328
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d710292c-42cd-463f-b92f-a2851d2f258b # Historical Period
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86fde8bb-f191-4b79-9fb3-768eb278c10d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-15T17:26:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a9d40f84-91b6-40fe-b6c1-14b3a4315c67 # Neighborhood
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43a9d15e-902d-4d1f-b27f-a31191b89535
            userCondition: null
            warning: null
            width: 100
        name: Taxonomy
        uid: 2abf2cae-4e99-499a-917b-6280b84a7cb9
        userCondition: null
    thumbFieldKey: null
handle: person
hasTitleField: false
icon: null
name: Person
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{fullName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
