columnSuffix: null
handle: groupWebsite
instructions: null
name: 'Group Website'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
