columnSuffix: null
handle: hasSubBoards
instructions: null
name: 'Has Sub-Boards'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
