columnSuffix: null
handle: mpWikipediaUrl
instructions: null
name: 'MP Wikipedia URL'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
