columnSuffix: null
handle: personGraveUrl
instructions: null
name: 'Person Find A Grave URL'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
