columnSuffix: null
handle: placeScvhlCheckbox
instructions: null
name: 'Place SCV Landmark'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
