defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e31f2a11-8bb9-4061-992b-119f6b2645fc # Person
handle: persons
maxAuthors: 1
name: Persons
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3ae144ef-e15a-4685-8fec-8ac0dfa20b68: # SCV History
    enabledByDefault: true
    hasUrls: true
    template: persons/_entry
    uriFormat: 'persons/{slug}'
type: channel
